version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: my-wallet-postgres
    environment:
      POSTGRES_DB: mywallet
      POSTGRES_USER: mywallet
      POSTGRES_PASSWORD: mywallet123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-wallet-network

volumes:
  postgres_data:

networks:
  my-wallet-network:
    driver: bridge
